### ISSUE TITLE
[Enhancement] Add parsing of genrules / match rules so that it's easily understood which conditions will match with a resource

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/codecollection-registry#6]
**Observation** 
For any codebundle that is "discoverable", we need a way to provide some additional content as to what conditions cause a match when workspace builder is scanning the repository and looking for matches. 

**Current Outcome** 
Currently we have to read the source code.  For example: 
```
apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - namespace
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: [name]
          mode: substring
```

**Desired Outcome**
A simple bit of text outlining the conditions that cause a match. Based on the above example, we might have some text that says: "Matches each namespace object in a cluster"
