### ISSUE TITLE
CodeBundle Score v1

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/codecollection-registry#9]
Add v1 of the script that can add a general score to each of the CodeBundles. It might be ideal to have a list of specific output items and then a final score, as the score itself would be somewhat "at-a-glance" and the output would help identify key elements of a CodeBundle. 

For example: 
- More than 1 task, less than 7
- Per task points: 
- SLI: pushes a metric (+1)
- RunBook: Adds to report (+1)
- RunBook: Raises an issue (+1)
- Runbook: Raises a dynamic issue (+2)
- Templates: SLI (+1)
- Templates: Runbook (+1)
- Basic robot linting?
- Total score = points / tasks

**Comment by stewartshea** [comment]
First step is a text checklist added to public docs, which will then turn into the script I suppose.

**Comment by stewartshea** [comment]
This, for v1, is getting pretty close to good enough. It's being packaged into a github action, and uses openai to help focus on task titles, as well as a few more checks. We can make this much more functional, but this might be a good starting point. 

https://github.com/runwhen-contrib/rw-generic-codecollection/actions/runs/13106029156


example action usage
```
name: Score CodeCollection
on: 
  workflow_dispatch:

jobs:
  score-codebundles:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # <-- This ensures we can push commits
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # so we can push back

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: runwhen-contrib/github-actions/codecollection-score@score
        with:
          directory: './codebundles'
          commit_results: true

```

https://github.com/runwhen-contrib/github-actions
